class ExploreRepo
    attr_reader :all_ingredients, :good_ingredients, :bad_ingredients, :good_ingredient_text, :bad_ingredient_text

    def initialize
        @all_ingredients = [
            "alcohol",
            "ashwinder eggs",
            "arcana rocks",
            "avocado",
            "beetle eye",
            "billywig stinger",
            "bitter root",
            "blood",
            "caterpillar",
            "chicken lips",
            "cockroach",
            "chess pawn",
            "death cap",
            "crowbane",
            "dragon dung",
            "snake skin",
            "fluxweed",
            "griffin claw",
            "gargoyle scale",
            "hermit crab shell",
            "horned slug",
            "horse hair",
            "kelp",
            "lizard's leg",
            "newt spleen",
            "pearl dust",
            "plantain",
            "dead puffer fish",
            "rat tail",
            "snake fang",
            "salt",
            "spiders",
            "frog's toe",
            "wolf tooth",
            "turtle",
            "wormwood",
            "aconite",
            "bat spleen",
            "unicorn urine",
            "iguana blood",
            "ink",
            "small bones",
            "cat hair",
            "crocodile heart",
            "dragon claw",
            "owl feather",
            "assorted eyeballs",
            "fairy wing",
            "frog brain",
            "ginger",
            "rubies",
            "lavender",
            "leech juice",
            "mandrake",
            "moonstone",
            "mushrooms",
            "newt oil",
            "octopus powder",
            "pickled slugs",
            "pixie wings",
            "ogre toenail",
            "silver",
            "sage",
            "star grass",
            "tongue of dog",
            "tarot cards",
            "toadstools",
            "water",
            "wizard's beard hairs",
            "gorgon tears",
            "cyclops sweat",
            "ancient dust",
            "rose petals",
            "damaged recipe: Witch's Brew => ['cat hair', 'b-']",
            "damaged recipe: Warlock's Brew => ['frog brain', 't---u- -- d--']",
            "\nKaz's journal:\n Year - 1743\n Moon: Garnet,\nIt reads: I've almost figured it out... the vial or Amortentia. I've tried and failed so many times, 
            but this moon will be different.\n I've discovered that the key ingredient isn't an ingredient at all, it's a potion!! 
            In fact all the ingredients are potions.\n This is my hypothesis, if you combine the Brew of visions w-"
        ]
        # Array of good ingredients found while exploring
        @good_ingredients = [
            "aconite",
            "ashwinder eggs",
            "arcana rocks",
            "bat spleen",
            "chess pawn",
            "unicorn urine",
            "iguana blood",
            "ink",
            "small bones",
            "cat hair",
            "crocodile heart",
            "dragon claw",
            "owl feather",
            "assorted eyeballs",
            "fairy wing",
            "frog brain",
            "ginger",
            "gargoyle scale",
            "rubies",
            "lavender",
            "leech juice",
            "mandrake",
            "moonstone",
            "mushrooms",
            "newt oil",
            "octopus powder",
            "pickled slugs",
            "pixie wings",
            "ogre toenail",
            "silver",
            "sage",
            "star grass",
            "tarot cards",
            "tongue of dog",
            "toadstools",
            "wizard's beard hairs",
            "gorgon tears",
            "cyclops sweat",
            "ancient dust",
            "rose petals"
        ]
        # Array of good ingredients found while exploring
        @bad_ingredients = [
            "alcohol",
            "avocado",
            "beetle eye",
            "billywig stinger",
            "bitter root",
            "blood",
            "caterpillar",
            "chicken lips",
            "cockroach",
            "death cap",
            "crowbane",
            "dragon dung",
            "snake skin",
            "fluxweed",
            "griffin claw",
            "hermit crab shell",
            "horned slug",
            "horse hair",
            "kelp",
            "lizard's leg",
            "newt spleen",
            "pearl dust",
            "plantain",
            "dead puffer fish",
            "rat tail",
            "snake fang",
            "salt",
            "spiders",
            "frog's toe",
            "wolf tooth",
            "turtle",
            "spectacles",
            "wormwood",
            "photo of Elisa",
            "broken glass",
            "water",
            "zephyr extract",
            "damaged pipe",
            "fractured vape",
            "special grass",
            "damaged recipe: Witch's Brew => ['cat hair', 'b-']",
            "damaged recipe: Warlock's Brew => ['frog brain', 't---u- -- d--']", 
            "\nKaz's journal:\n Year - 1743\n Moon: Garnet,\nIt reads: I've almost figured it out... the vial or Amortentia. I've tried and failed so many times, 
            but this moon will be different.\n I've discovered that the key ingredient isn't an ingredient at all, it's a potion!! 
            In fact all the ingredients are potions.\n This is my hypothesis, if you combine the Brew of visions w-"
        ]
        # Array of things to say when a good ingredient is found
        @good_ingredient_text = [
            "Another stellar ingredient to add to my collection",
            "Keep that, we might need it later",
            "NYAAAKAKAAA that's what I'm talking about!",
            "Wow, that's a good find! I'm sure we can use this",
            "Oooh, not bad. We'll take this back",
            "Hmmm, I think I know what we can use this for... Let's grab it",
            "We definitely need this",
            "Finders keepers!"
        ]
        # Array of things to say when a good ingredient is found
        @bad_ingredient_text = [
            "Quit wasting time and find me something useful.",
            "I can't imagine what anyone would do with this?",
            "Oh hell no, we don't need that!",
            "Umm.... I think it's safe to say we don't need this",
            "Eww, no. Put it back",
            "I have too many of these already, no thanks",
            "Wow, that's a good fine! Too bad it's not useful for potions.",
            "Throw that away now!"
        ]
    end
end